on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4 # Updated to newer version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache libffi-dev libssl-dev python3-dev python3-venv python3-wheel libsqlite3-dev sqlite3 libgmp-dev zlib1g-dev openjdk-17-jdk unzip
          pip install --upgrade cython virtualenv
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: .buildozer/android/platform/build-*/outputs/apk/debug/*.apk
